In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3,4])
b = np.array([0,0.5,1,1.5,2])

In [4]:
a[0],a[1]

(1, 2)

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[1:3]

array([2, 3])

In [7]:
a[1:-1]

array([2, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0,2,-1]]

array([0., 1., 2.])

In [14]:
a.dtype

dtype('int32')

In [175]:
a.nbytes

16

In [176]:
a.itemsize

4

In [15]:
np.array([1,2,3,4],dtype=np.float64)

array([1., 2., 3., 4.])

In [16]:
c = np.array(['a','b','c'])
c.dtype

dtype('<U1')

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [6]:
A.shape
A.size
A.ndim

2

In [16]:
B = np.array([
    [
        [1,2,3],
        [4,5,6],
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [17]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
C = np.full((2,2,3),5)
C

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [19]:
print(B*C)
C**3

[[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]]


array([[[125, 125, 125],
        [125, 125, 125]],

       [[125, 125, 125],
        [125, 125, 125]]], dtype=int32)

In [29]:
B.shape
B.size
B.ndim
B.dtype

dtype('int32')

# Indexing and Slicing of Matrices

In [31]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [33]:
A[1]

array([4, 5, 6])

In [35]:
A[1][0]
A[1,0]

4

In [36]:
A[0:2] #Excludes 2 

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [38]:
A[:2,2:]

array([[3],
       [6]])

In [53]:
A

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

### fancy indexing

In [31]:
arr1 = np.arange(32).reshape(8,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr1[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

# Statistics

In [54]:
a= np.array([1,2,3,4])

In [55]:
a.sum()

10

In [56]:
a.mean()

2.5

In [58]:
a.std()

1.118033988749895

In [59]:
a.var()

1.25

In [70]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
A.sum()

45

In [73]:
A.mean()

5.0

In [75]:
A.std()

2.581988897471611

In [76]:
A.sum(axis=0)

array([12, 15, 18])

In [77]:
A.sum(axis=1)

array([ 6, 15, 24])

In [79]:
A.mean(axis=1)

array([2., 5., 8.])

In [80]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [49]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
squqre_root = np.sqrt(array)
squqre_root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [52]:
exp = np.exp(array)
exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
x = np.random.randn(8)
y = np.random.randn(8)

np.maximum(x,y)

array([ 2.47110423,  0.07545801,  0.53522374,  0.57691103,  1.1242337 ,
        2.26934117, -0.29323651,  1.0268836 ])

In [59]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
array.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

# Broadcasting and vectorized operations

In [82]:
a = np.arange(6)

In [83]:
a

array([0, 1, 2, 3, 4, 5])

In [84]:
a + 10

array([10, 11, 12, 13, 14, 15])

In [85]:
a*10

array([ 0, 10, 20, 30, 40, 50])

In [86]:
a

array([0, 1, 2, 3, 4, 5])

In [87]:
a+=100

In [88]:
a

array([100, 101, 102, 103, 104, 105])

In [95]:
x = np.arange(5)
y = np.arange(5)

In [96]:
x+y

array([0, 2, 4, 6, 8])

In [97]:
x*y

array([ 0,  1,  4,  9, 16])

# Boolean array

In [100]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [101]:
a>=2

array([False, False,  True,  True])

In [102]:
a.mean()

1.5

In [104]:
a[a>a.mean()]

array([2, 3])

In [105]:
a[~(a>a.mean())]

array([0, 1])

In [115]:
A = np.random.randint(100,size=(3,3))

In [116]:
A

array([[57, 60,  6],
       [19,  7, 94],
       [42, 46, 61]])

In [117]:
A>30

array([[ True,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

In [118]:
A[A>30]

array([57, 60, 94, 42, 46, 61])

# Linear Algebra

In [121]:
A = np.random.randint(10,size =(3,3))

In [122]:
A

array([[4, 9, 2],
       [2, 3, 6],
       [9, 7, 9]])

In [130]:
B = np.random.randint(5,size=(3,3))
B

array([[4, 1, 1],
       [1, 0, 3],
       [1, 2, 0]])

In [131]:
A.dot(B)

array([[27,  8, 31],
       [17, 14, 11],
       [52, 27, 30]])

# Useful numpy function

## random

In [132]:
np.random.random(size=5)

array([0.59274304, 0.20916528, 0.73207162, 0.82523691, 0.67839326])

In [133]:
np.random.normal(size = 3)

array([ 1.48198559,  1.38036304, -0.85844082])

In [134]:
np.random.rand(2,3)

array([[0.82215225, 0.48989523, 0.08583108],
       [0.14733081, 0.0739123 , 0.61641036]])

In [135]:
np.random.randint(10,size=(4,4))

array([[6, 9, 4, 0],
       [3, 3, 0, 0],
       [0, 2, 9, 5],
       [1, 5, 2, 4]])

## arange

In [136]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [137]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [139]:
np.arange(0,1,.1)
np.arange(10,20,3)

array([10, 13, 16, 19])

## reshape

In [140]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## linspace

In [143]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [144]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [150]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## zeroes,ones,empty

In [154]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [156]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [157]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [158]:
np.empty((2,3))

array([[0.82215225, 0.48989523, 0.08583108],
       [0.14733081, 0.0739123 , 0.61641036]])

## identity and eye

In [159]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [160]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [163]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
np.eye(8,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

# Repeat (keith galli)

In [204]:
a = np.array([[1,2,3,4,5]])
a1 = np.repeat(a,3,axis =1)

In [205]:
a1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [206]:
a2 = np.repeat(a,4,axis = 0)

In [207]:
a2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [216]:
z = np.ones((5,5))
z[1:4,1:-1]=0
z[2,2]=9
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
b= np.array([6,7,8,9,10])
print(b)


[ 6  7  8  9 10]


In [8]:
a*b

array([ 6, 14, 24, 36, 50])

# Changing values in array

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr3d[0]=20

In [27]:
arr3d

array([[[20, 20, 20],
        [20, 20, 20]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Transposing Arrays and Swapping Axes

In [41]:
a = np.arange(16).reshape(4,4)
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [45]:
b = np.arange(16).reshape(2,2,4)
b.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [61]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [47]:
b.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])